### ISSUE TITLE
nft java api

### ISSUE THREAD

**Issue by jxl0506** [Conflux-Chain/java-conflux-sdk#36]
没有nft相关的java api吗

**Comment by Pana** [comment]
Java-SDK have support for standard tokens include ERC721, ERC1155, you can use them interact with NFTs

**Comment by jxl0506** [comment]
麻烦提供下创建nft（mint）的java示例代码

**Comment by jxl0506** [comment]
是否能提供一份java创建nft的示例代码。我使用如下代码无法创建成功，jxlKey是我账户的私钥，contractAddr是我创建的nft合约的地址
Account account= Account.create(cfx, jxlKey);
ERC721 erc721 = new ERC721(cfx, new CfxAddress(contractAddr), account);
Account.Option option = new Account.Option();
try {
    String result = erc721._mint(option, new CfxAddress(jxlAddr), BigInteger.valueOf(tokenId));
System.out.println("mint result : " + result);
} catch (Exception e) {
    e.printStackTrace();
}
